version: '3.1'

services:

  db:
    image: mariadb:lts-noble
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: equipment
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:/Users/war4m/OneDrive/Desktop/project/CSVToMariaDb/mariadb